### ISSUE TITLE
Can't get changes for a bundle with availability-zone constraints

### ISSUE THREAD

**Issue by huwshimi** [juju/bundleservice#4]
When I try and deploy a bundle with availability zones e.g.

```

machines: 
  "0": 
    series: precise
    constraints: "arch=amd64 cpu-cores=1 cpu-power=300 mem=3840 root-disk=8192 availability-zone=ap-southeast-2a"
```

I get this follow error:

`The following errors occurred while retrieving bundle changes: invalid constraints "arch=amd64 cpu-cores=1 cpu-power=300 mem=3840 root-disk=8192 availability-zone=ap-southeast-2b" in machine "1": unknown constraint "availability-zone", invalid constraints "arch=amd64 cpu-cores=1 cpu-power=300 mem=3840 root-disk=8192 availability-zone=ap-southeast-2a" in machine "0": unknown constraint "availability-zone"`
